// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3LID9k41XfyV3-V8qNkzIsaE1actMp-g',
    appId: '1:18021718333:web:e93923656c3480e1554d54',
    messagingSenderId: '18021718333',
    projectId: 'odee-d7f31',
    authDomain: 'odee-d7f31.firebaseapp.com',
    storageBucket: 'odee-d7f31.appspot.com',
    measurementId: 'G-YGEN9WLEBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFZTsHKlhTSaHPP6NAgCEqIn28T-ajwNo',
    appId: '1:18021718333:android:a88bf8216164d2e9554d54',
    messagingSenderId: '18021718333',
    projectId: 'odee-d7f31',
    storageBucket: 'odee-d7f31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt1nlzv56RLjG6TNaczAT7q0mKe9tjwqI',
    appId: '1:18021718333:ios:964ab82f18b8da26554d54',
    messagingSenderId: '18021718333',
    projectId: 'odee-d7f31',
    storageBucket: 'odee-d7f31.appspot.com',
    iosClientId: '18021718333-2e7vm2l3rkpdnn5ikfd2u5ohs75vjnap.apps.googleusercontent.com',
    iosBundleId: 'com.example.odeeFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt1nlzv56RLjG6TNaczAT7q0mKe9tjwqI',
    appId: '1:18021718333:ios:964ab82f18b8da26554d54',
    messagingSenderId: '18021718333',
    projectId: 'odee-d7f31',
    storageBucket: 'odee-d7f31.appspot.com',
    iosClientId: '18021718333-2e7vm2l3rkpdnn5ikfd2u5ohs75vjnap.apps.googleusercontent.com',
    iosBundleId: 'com.example.odeeFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3LID9k41XfyV3-V8qNkzIsaE1actMp-g',
    appId: '1:18021718333:web:f678ca61ad6b1c72554d54',
    messagingSenderId: '18021718333',
    projectId: 'odee-d7f31',
    authDomain: 'odee-d7f31.firebaseapp.com',
    storageBucket: 'odee-d7f31.appspot.com',
    measurementId: 'G-G3YN6992YF',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB3LID9k41XfyV3-V8qNkzIsaE1actMp-g',
    appId: '1:18021718333:web:c9d54e6b19e3e767554d54',
    messagingSenderId: '18021718333',
    projectId: 'odee-d7f31',
    authDomain: 'odee-d7f31.firebaseapp.com',
    storageBucket: 'odee-d7f31.appspot.com',
    measurementId: 'G-R303SERRM0',
  );
}
